<h1><center>Laboratorio 4: El Pandas no muerde (act. I) üêº</center></h1>

<center><strong>MDS7202: Laboratorio de Programaci√≥n Cient√≠fica para Ciencia de Datos</strong></center>

### Cuerpo Docente:

- Profesor: Pablo Badilla y Ignacio Meza D.
- Auxiliar: Sebasti√°n Tinoco
- Ayudante: Felipe Arias y Diego Cortez

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no ser√°n revisados

- Nombre de alumno 1: Lennin Chamorro
- Nombre de alumno 2: Mart√≠n Reyes

### **Link de repositorio de GitHub:** `https://github.com/Landilus/Lab_prog_cientifica/tree/Lab_4_Pandas`

### Reglas:

- **Grupos de m√°ximo 2 personas**
- Asistencia **obligatoria** a instrucciones del lab (viernes 16.15). Luego, pueden quedarse trabajando en las salas o irse.
- **No se revisar√°n entregas de personas ausentes**. 
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente ser√°n respondidos por este medio.
- Prohibidas las copias. 
- Pueden usar cualquer matrial del curso que estimen conveniente.

### Temas a tratar

- Introducci√≥n al manejo de datos tabulares por medio de la libreria `pandas`.

### Objetivos principales del laboratorio

- Entender, aplicar y aprovechar las ventajas que nos ofrece la libreria `pandas` para manejar datos tabulares.
- Aprender a utilizar la documentaci√≥n de pandas (y en general, de cualquier librer√≠a de python) como tambi√©n a buscar soluciones en la web.

> **Nota**: El laboratorio deber√° ser desarrollado sin el uso indiscriminado de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al m√°ximo las funciones optimizadas que nos entrega `pandas`, las cuales vale mencionar, son bastante m√°s eficientes que los iteradores nativos sobre DataFrames.

### Librerias utiles para el Lab üò∏

In [1]:
# Libreria Core del lab.
import numpy as np
import pandas as pd
from IPython.display import display

#Libreria para plotear
!pip install --upgrade plotly
import plotly.express as px
import plotly.graph_objects as go

# Librerias utiles
from sklearn.preprocessing import StandardScaler

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (5.13.1)
Collecting plotly
  Downloading plotly-5.14.1-py2.py3-none-any.whl (15.3 MB)
     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 15.3/15.3 MB 75.4 MB/s eta 0:00:00
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly) (8.2.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly) (23.1)
Installing collected packages: plotly
  Attempting uninstall: plotly
    Found existing installation: plotly 5.13.1
    Uninstalling plotly-5.13.1:
      Successfully uninstalled plotly-5.13.1
Successfully installed plotly-5.14.1

# 1. Rendimiento en Estudiantes üìö

Para este laboratorio deber√°n trabajar con el dataset `students_grades.json` el cual contiene informaci√≥n sobre el rendimiento de alumnos en distintos ramos. 
El objetivo principal ser√° el de realizar un trabajo de limpieza de prepraci√≥n y exploraci√≥n de datos utilizando exclusivamente `DataFrames` y sus m√©todos asociados.

In [3]:
# Si usted est√° utilizando Colabolatory le puede ser √∫til este c√≥digo para cargar los archivos.
try:
    from google.colab import drive
    drive.mount("/content/drive")
    path = '/content/drive/MyDrive/Colab Notebooks/LPC/Datos_Lab4/students_grades.json'
except: 
    print('Ignorando conexi√≥n drive-colab')

Mounted at /content/drive

## 1.1 Carga e Inspecci√≥n de Datos [1.5 Puntos]


<p align="center">
  <img src="https://drive.google.com/uc?export=view&id=1hZZaPQlZe4VupFOXt76_wjuUA5NpUhrw" width="300" height="300">
</p>

*Don Caguayo*, rector de la Universidad de la Cacha√±a, les comenta que actualmente la Universidad no tiene una subdirecci√≥n de an√°lisis de datos, pero que tiene un gran inter√©s en formar una. Es por esto, que se contacta con ud. y su equipo para iniciar de forma exploratoria diversas tareas de an√°lisis y consolidaci√≥n de datos respectivos al rendimiento de sus alumnos.

Previo a su primera reuni√≥n con el rector, el rector le env√≠a una copia de la base de datos, la cu√°l a usted y su equipo le encantar√≠a examinar. Para esto, la primera tarea que debe realizar es abrir y cargar el dataset. 


> **Notar que es sumamente importante el formato que posee cada columna** para su manipulaci√≥n y que posiblemente ustedes deber√°n especificar algunos tipos de datos a mano. Ver la documentaci√≥n del m√©todo `read_json` para mayor informaci√≥n.

A continuaci√≥n se muestra un ejemplo de los dos primeros registros del dataset:

```json
[
  {
    "names": "Rita Courtney",
    "gender": "female",
    "race/ethnicity": "group B",
    "parental level of education": "some high school",
    "lunch": "standard",
    "test preparation course": "none",
    "math score": 37,
    "reading score": 46,
    "writing score": 46
  },
  {
    "names": "Madeline Fuller",
    "gender": "female",
    "race/ethnicity": "group C",
    "parental level of education": "some high school",
    "lunch": "standard",
    "test preparation course": "none",
    "math score": 124,
    "reading score": 142,
    "writing score": 142
  }
]
```

In [4]:
df_grades = pd.read_json('/content/drive/MyDrive/Colab Notebooks/LPC/Datos_Lab4/students_grades.json')
df_grades.replace('', np.nan, inplace=True)


<p align="center">
  <img src="https://i.giphy.com/media/4FQMuOKR6zQRO/giphy.webp">
</p>


Posteriormente, el rector les comenta que la secci√≥n de TI posee una base de datos con m√°s de **875** filas, en donde cada fila representa un alumno matriculado. Sin embargo, cree fuertemente que existen errores en esta: solo tiene registro de **875** matriculas. Por este motivo, especula que se han realizado malas pr√°cticas al registrar dichos datos.

En consecuencia, el rector les solicita a ustedes como tarea inicial que exploren la base de datos y encuentre posibles falencias dentro de sus registros. Para esto, usted debe estar al tanto que las notas est√°n en una escala que van del **0 al 100** (porcentaje de logro) y **no es posible que un alumno haya dado m√°s de una vez el mismo examen**. Cualquier alumno que posea un valor diferente a esta escala, deber√≠a ser eliminado de la base de datos.

> **Instrucciones**

**Cree una funci√≥n** que tome un `DataFrame` y que le permita revisar si las diferentes variables que lo componen son coherentes y si es posible observar anomal√≠as en estas. 

**To-Do**
1. [ ] Imprimir un mensaje con las dimensiones del Dataframe.
2. [ ] Imprimir un mensaje con los nombres de las columnas que conforman el DataFrame.
3. [ ] Mostrar los primeros 5, los √∫ltimos 5 elementos del DataFrame y realice un muestreo de 5 elementos de forma aleatoria.
4. [ ] Mostrar una descripci√≥n r√°pida de las variables num√©ricas del DataFrame (utilice un m√©todo visto en clases).
5. [ ] Imprimir un mensaje con la cantidad de valores nulos (investigue el m√©todo `isna()` y `sum()` de los DataFrames).
6. [ ] Imprimir un mensaje que detalle la cantidad de valores unicos (investigue `nunique()`) .
7. [ ] Imprimir un mensaje con el total de filas que contengan nombres duplicados (investigue `duplicated()` y su par√°metro `subset`).
8. [ ] Mostrar las filas que contengan nombres sean duplicados (investigue `duplicated()` y su par√°metro `subset`).
9. [ ] A traves de `.plot.box()` plotear el boxplot de las notas. De ser necesario, invetigue como funcionan los gr√°ficos de caja (esta secci√≥n es provista).
10. [ ] Finalmente responda la siguiente pregunta:

> ¬øQue anomalias es posible observar de los datos que componen el DataFrame? ¬øExisten valores nulos o duplicados? ¬øQu√© puede interpretar de la distribuci√≥n de las notas en el boxplot? (), comente esto en la celda ubicada debajo de **justificaci√≥n**.

> **Nota:** Para imprmir utilice `print(...)`. Para mostrar `DataFrames`, utilice `display(...)` ya que este permite mostrar estos elementos como tablas.

> **Nota 2:** Utilice la documentaci√≥n de [pandas](https://pandas.pydata.org/docs/index.html) como tambi√©n StackOverflow para resolver cualquier problema o inconveniente.

> **Nota 3:** Si no ha trabajado con boxplot antes, el siguiente link puede serle de mucha ayuda: [boxplot](https://medium.com/dayem-siddiqui/understanding-and-interpreting-box-plots-d07aab9d1b6c)

**Respuesta:**

In [23]:
def exploratory_data_analysis(dataframe):
    import matplotlib.pyplot as plt 
    print(f'1.- El DataFrame tiene {dataframe.shape[0]} filas y {dataframe.shape[1]} columnas')
    print('')
    print(f'2.- El DataFrame esta compuesto por las siguientes columnas {list(dataframe.columns)}')
    print('')
    #print('las columnas que conforman el dataframe son ' + ', '.join(dataframe.columns))
    print(f'3.- Ejemplos de filas del DataFrame:')
    print('')
    print(f'Primeras 5 filas:')
    print('')
    display(dataframe.head(5))
    print('')
    print(f'√öltimass 5 filas:')
    print('')
    display(dataframe.tail(5))
    print('')
    print(f'Muestreo aleatorio de 5 filas:')
    print('')
    display(dataframe.sample(5))
    print('')
    print(f'4.- Descripci√≥n num√©rica del dataframe:')
    print('')
    display(dataframe.describe())
    print('')
    print(f'5.- Cantidad de valores n√∫los por columna:')
    print('')
    print(dataframe.isna().sum()) 
    print('')
    print(f'6.- Cantidad de valores √∫nicos por columna:')
    print('')
    print(dataframe['names'].nunique())
    print('')
    n_rep = dataframe.duplicated(subset =['names']).sum()
    print('')
    print(f'7.- Presenta un total de {n_rep} filas con nombres duplicados.')
    print('')
    print(f'8.- Las filas con nombres duplicados son:')
    print('')
    display(dataframe[dataframe.duplicated(subset = ['names'])])
    print('')
    print(f'boxplot de notas:')
    print('')
    fig = go.Figure()
    fig.add_trace(go.Box(y=df_grades['math score'], name='math score'))
    fig.add_trace(go.Box(y=df_grades['reading score'], name='reading score' ))
    fig.add_trace(go.Box(y=df_grades['writing score'], name= 'writing score'))
    fig.update_layout(title='Scores for Math, Reading and Writing', yaxis_title='Score', legend_title = 'Subject')
    fig.show()

In [22]:
exploratory_data_analysis(df_grades)

1.- El DataFrame tiene 1400 filas y 9 columnas

2.- El DataFrame esta compuesto por las siguientes columnas ['names', 'gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']

3.- Ejemplos de filas del DataFrame:

Primeras 5 filas:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
1,Madeline Fuller,female,group C,some high school,standard,none,124.0,142.0,142.0
2,Daniel Rester,male,group E,associate's degree,standard,none,156.0,196.0,193.0
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
4,Geraldine Hale,female,group A,associate's degree,standard,none,131.0,166.0,166.0

√öltimass 5 filas:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1395,Alexander Dillon,male,group D,associate's degree,standard,none,193.0,142.0,193.0
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193.0,196.0,193.0
1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0

Muestreo aleatorio de 5 filas:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
353,Mary Ramirez,female,group C,associate's degree,standard,none,124.0,193.0,193.0
582,Barbara Torres,female,group D,some college,free/reduced,none,49.0,65.0,61.0
278,Audrey Love,female,group B,bachelor's degree,standard,none,67.0,86.0,83.0
241,Anthony Casey,male,group A,bachelor's degree,standard,none,64.0,60.0,58.0
216,Miranda Domingo,female,group D,some college,standard,none,196.0,193.0,124.0

4.- Descripci√≥n num√©rica del dataframe:

        math score  reading score  writing score
count  1360.000000    1360.000000    1353.000000
mean     89.538971      93.086029      91.852919
std      47.152422      46.385775      47.043570
min       0.000000      17.000000      10.000000
25%      59.000000      63.000000      62.000000
50%      72.000000      76.000000      75.000000
75%      97.250000     100.000000     100.000000
max     196.000000     196.000000     196.000000

5.- Cantidad de valores n√∫los por columna:

names                           0
gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                     40
reading score                  40
writing score                  47
dtype: int64

6.- Cantidad de valores √∫nicos por columna:

1153


7.- Presenta un total de 247 filas con nombres duplicados.

8.- Las filas con nombres duplicados son:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
12,Rita Courtney,female,group B,some high school,standard,none,193.0,193.0,193.0
81,Elizabeth Quintero,female,group B,some college,standard,none,82.0,85.0,87.0
160,Michelle Gonzales,female,group B,some high school,standard,completed,60.0,70.0,74.0
170,Carla Mendoza,female,group D,associate's degree,free/reduced,none,43.0,60.0,58.0
176,Darlene Parker,female,group C,associate's degree,standard,none,54.0,61.0,58.0
...,...,...,...,...,...,...,...,...,...
1385,James Crawford,male,group D,master's degree,standard,none,193.0,147.0,131.0
1390,Gloria Bradford,female,group B,high school,standard,none,124.0,64.0,193.0
1393,Adam Romero,male,group C,high school,standard,completed,124.0,193.0,49.0
1395,Alexander Dillon,male,group D,associate's degree,standard,none,193.0,142.0,193.0
1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193.0,196.0,193.0

boxplot de notas:

**Justificaci√≥n:**

```
La primera observaci√≥n que resalta del data set son los valores duplicados, claramente hubo problemas al registrar a los estudiantes y sus resultados en las evaluaciones, lo cual se visualiza en que existen 247 filas que deberemos eliminar.
Del registro de valores √∫nicos podriamos considerar que la cantidad de alumnos del establecimiento es 1153 y no 875 como dice el rector, pues es la cantidad de valores unicos en la columna nombres y coincide con las celdas no duplicadas.

El siguiente elemento que destaca es las estadisticas de las columnas num√©ricas, vemos que los maximos se escapan de los valores especificados por el rector pues hay calificaciones de m√°s de 190, la media y la desviaci√≥n estandar son muy altas, lo cual implica que almenos un 25% de los datos estan con sus calificaciones mal puestas.

Tambien vemos que hay registros de alumnos que tienen sus calificaciones nulas, esto podria interpretarse como un error en el tipeo o que los alumnos no rindieron sus evaluaciones, a lo cual habria que reemplazar los nulos con la calificacion m√≠nima para hacer los analisis o sacarlos del set de datos.
```

**Respuesta Esperada:**

In [ ]:
exploratory_data_analysis(df_grades)

1.- El DataFrame tiene 1400 filas y 9 columnas

2.- El DataFrame esta compuesto por las siguientes columnas: ['names', 'gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']

3.- Ejemplos de filas del DataFrame:

Primeras 5 filas:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
1,Madeline Fuller,female,group C,some high school,standard,none,124.0,142.0,142.0
2,Daniel Rester,male,group E,associate's degree,standard,none,156.0,196.0,193.0
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
4,Geraldine Hale,female,group A,associate's degree,standard,none,131.0,166.0,166.0

√öltimas 5 filas:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1395,Alexander Dillon,male,group D,associate's degree,standard,none,193.0,142.0,193.0
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193.0,196.0,193.0
1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0

Muestreo aleatorio de 5 filas:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1282,Alberto Roberts,male,group D,associate's degree,standard,none,52.0,55.0,49.0
604,Ronald Wilson,male,group C,some high school,standard,none,64.0,58.0,51.0
559,Christine Reed,female,group E,bachelor's degree,standard,completed,188.0,142.0,131.0
380,Edna Johnson,female,group E,some college,standard,completed,193.0,124.0,196.0
1392,Richard Young,male,group D,high school,standard,none,69.0,75.0,71.0

4.- Descripci√≥n num√©rica del Dataframe:

        math score  reading score  writing score
count  1360.000000    1360.000000    1353.000000
mean     89.538971      93.086029      91.852919
std      47.152422      46.385775      47.043570
min       0.000000      17.000000      10.000000
25%      59.000000      63.000000      62.000000
50%      72.000000      76.000000      75.000000
75%      97.250000     100.000000     100.000000
max     196.000000     196.000000     196.000000

5.- Cantidad de valores nulos por columna:

names                           0
gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                     40
reading score                  40
writing score                  47
dtype: int64

6.- Cantidad de valores √∫nicos por columna:

names                          1153
gender                            2
race/ethnicity                    5
parental level of education       6
lunch                             2
test preparation course           2
math score                       96
reading score                    88
writing score                    92
dtype: int64

7.- Presenta un total de 247 filas con nombres duplicados.

8.- Las filas con nombres duplicados son:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
12,Rita Courtney,female,group B,some high school,standard,none,193.0,193.0,193.0
81,Elizabeth Quintero,female,group B,some college,standard,none,82.0,85.0,87.0
160,Michelle Gonzales,female,group B,some high school,standard,completed,60.0,70.0,74.0
170,Carla Mendoza,female,group D,associate's degree,free/reduced,none,43.0,60.0,58.0
176,Darlene Parker,female,group C,associate's degree,standard,none,54.0,61.0,58.0
...,...,...,...,...,...,...,...,...,...
1385,James Crawford,male,group D,master's degree,standard,none,193.0,147.0,131.0
1390,Gloria Bradford,female,group B,high school,standard,none,124.0,64.0,193.0
1393,Adam Romero,male,group C,high school,standard,completed,124.0,193.0,49.0
1395,Alexander Dillon,male,group D,associate's degree,standard,none,193.0,142.0,193.0
1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193.0,196.0,193.0

9.- Boxplot de notas:

## 1.2 Limpieza de Datos [1 punto]

<p align="center">
  <img src="https://blogdatlas.files.wordpress.com/2020/07/datlas_mx_blog_limpieza_bds_data-scrubbing-service.gif">
</p>

En base a lo realizado anteriormente, realice una limpieza de los dataset. Asuma los supuestos se√±alados en la pregunta anterior para limpiar el `DataFrame` y cree una funci√≥n que le permita limpiar los datos. Habiendo limpiado el `DataFrame`, compruebe nuevamente los datos con la funci√≥n creada en la secci√≥n 1.1.

**To-Do:**

- [ ] Crear funci√≥n que permita limpiar el dataset.
- [ ] Comprobar que no existen anomal√≠as en los datos a traves de la funci√≥n de la secci√≥n 1.1.

**Hint**

Puede ser √∫til los m√©todos ```.drop_duplicates()``` y ```.dropna()``` como tambi√©n utilizar queries con m√°scaras booleanas.

**Respuesta:**

In [25]:
def clean_data(dataframe):
  print('El n√∫mero total de valores NaN en el dataframe es:', dataframe.isna().sum().sum())
  print('El n√∫mero total de nombres √∫nicos en el dataframe es:', dataframe['names'].nunique())
  print('El n√∫mero total de nombres duplicados en el dataframe es:', dataframe.duplicated(subset = ['names']).sum())
  df_clean = dataframe.copy()
  df_clean = df_clean.drop_duplicates(['names'])
  df_clean = df_clean.dropna()
  df_clean = df_clean[(df_clean['math score']<=100) & (df_clean['math score']>0) & (df_clean['reading score']<=100) & (df_clean['reading score']>0) & (df_clean['writing score']<=100) & (df_clean['writing score']>0)]
  print('El n√∫mero total de valores NaN en el dataframe es:', df_clean.isna().sum().sum())
  print('El n√∫mero total de nombres √∫nicos en el dataframe es:', df_clean['names'].nunique())
  print('El n√∫mero total de nombres duplicados en el dataframe es:', df_clean.duplicated(subset = ['names']).sum())
  return df_clean

In [26]:
df_grades = clean_data(df_grades)
df_grades

El n√∫mero total de valores NaN en el dataframe es: 127
El n√∫mero total de nombres √∫nicos en el dataframe es: 1153
El n√∫mero total de nombres duplicados en el dataframe es: 247
El n√∫mero total de valores NaN en el dataframe es: 0
El n√∫mero total de nombres √∫nicos en el dataframe es: 874
El n√∫mero total de nombres duplicados en el dataframe es: 0

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0
6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0
7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0
...,...,...,...,...,...,...,...,...,...
1392,Richard Young,male,group D,high school,standard,none,69.0,75.0,71.0
1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0

> Utilice la funci√≥n creada en el punto 1.1 para verificar sus resultados.

In [27]:
exploratory_data_analysis(df_grades)

1.- El DataFrame tiene 874 filas y 9 columnas

2.- El DataFrame esta compuesto por las siguientes columnas ['names', 'gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']

3.- Ejemplos de filas del DataFrame:

Primeras 5 filas:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0
6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0
7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0

√öltimass 5 filas:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1392,Richard Young,male,group D,high school,standard,none,69.0,75.0,71.0
1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0

Muestreo aleatorio de 5 filas:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
61,David Fisk,male,group D,bachelor's degree,standard,none,69.0,58.0,57.0
557,Michael Hughes,male,group B,some college,free/reduced,none,55.0,55.0,47.0
1367,Gregory Fernandez,male,group E,high school,free/reduced,completed,57.0,56.0,54.0
921,Agatha Bergman,female,group D,master's degree,standard,none,92.0,100.0,100.0
983,James Verhaag,male,group D,high school,free/reduced,completed,78.0,77.0,80.0

4.- Descripci√≥n num√©rica del dataframe:

       math score  reading score  writing score
count  874.000000     874.000000     874.000000
mean    66.300915      69.255149      68.180778
std     14.917715      14.530534      15.054823
min      8.000000      23.000000      15.000000
25%     57.000000      59.000000      58.000000
50%     66.000000      70.000000      69.000000
75%     76.750000      79.000000      79.000000
max    100.000000     100.000000     100.000000

5.- Cantidad de valores n√∫los por columna:

names                          0
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

6.- Cantidad de valores √∫nicos por columna:

874


7.- Presenta un total de 0 filas con nombres duplicados.

8.- Las filas con nombres duplicados son:

Empty DataFrame
Columns: [names, gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []

boxplot de notas:

**Justificaci√≥n:**

```
La limpieza comenzo con la eliminaci√≥n de los datos duplicados, pues es informaci√≥n redundante que no es necesaria en este Dataset.

En seg√∫ndo lugar se prefirio hacer la eliminaci√≥n tanto de los datos nulos como aquellos cuyas calificaciones son superiores a la escala entregada por el rector de la universidad.

Al hacer esto el resultado  coincide con el numero de alumnos matriculados que el rector menciona. Lo cual nos diria que las filas adicionales son datos erroneos.
```

## 1.3 Trabajando con Datos

<p align="center">
  <img src="https://media3.giphy.com/media/YQitE4YNQNahy/giphy-downsized-large.gif">
</p>

### 1.3.1 Transformaci√≥n de notas a "Nota Chilena" [0.5 Puntos]

En una de las reuniones con Don Caguayo este les comenta su intenci√≥n de pasar todas sus notas a la "Escala Chilena". Para esto les facilita la siguiente ecuaci√≥n:

$$Nota \, Chilena= \% \, de \, logro*0.06 + 1$$

Utilizando la ecuaci√≥n entregada, cree una funci√≥n que le permita pasar a la escala Chilena las notas que se escapan del rango [1,7] y entregue las notas redondeadas al segundo decimal.

**To-Do**

- [ ] Tranforme los valores a la escala chilena.

**Respuesta:**

In [28]:
def nota_chilena(dataframe_in, columna):
  def notach(nota):
    return nota * 0.06 + 1
  df = dataframe_in.copy()
  df[columna] = df[columna].apply(notach)
  return df

In [29]:
df_chile = nota_chilena(df_grades, 'reading score')
df_chile = nota_chilena(df_chile, 'math score')
df_chile = nota_chilena(df_chile, 'writing score')

In [44]:
df_chile.describe()

       math score  reading score  writing score
count  874.000000     874.000000     874.000000
mean     4.978055       5.155309       5.090847
std      0.895063       0.871832       0.903289
min      1.480000       2.380000       1.900000
25%      4.420000       4.540000       4.480000
50%      4.960000       5.200000       5.140000
75%      5.605000       5.740000       5.740000
max      7.000000       7.000000       7.000000

### 1.3.2 Obtenci√≥n de promedio de alumnos [0.5]

Con todas las notas adjuntadas, la prestigiosa Universidad De la Cacha√±a necesita obtener el promedio general de cada uno de los alumnos. Para esto se le solicita que calcule el promedio con cada una de las asignaturas y el promedio se anexe como una nueva columna al final del `DataFrame` original. Cabe se√±alar que las notas deben ser redondeadas al segundo decimal.

**To-Do:**
- [ ] Crear funci√≥n que nos permite obtener el promedio de cada uno de los alumnos y anexar esta informaci√≥n en el `DataFrame` original.

**Respuesta:**

In [45]:
def alumnos_promedio(dataframe_in):
  resp = dataframe_in.copy()
  resp['GPA'] = (resp['math score']+resp['reading score']+resp['writing score'])/3
  return resp

**Respuesta Esperada:**

In [46]:
df_grades = alumnos_promedio(df_chile)
df_grades.head()

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,GPA
0,Rita Courtney,female,group B,some high school,standard,none,3.22,3.76,3.76,3.58
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,5.80,5.68,5.86,5.78
5,Brian Young,male,group C,some high school,standard,none,5.38,4.96,4.78,5.04
6,Howard Jimenez,male,group E,some high school,standard,completed,5.86,5.50,5.56,5.64
7,Wayne Wilson,male,group B,some high school,standard,completed,6.64,6.16,6.22,6.34

### 1.3.3 Reprobados y Destacados [1.5 Punto, 0.5 Cada DataFrame]

Contentos con su desempe√±o, la Universidad les solicita que obtengan los alumnos quienes han reprobado el a√±o y los que han tenido desempe√±o de destacado. Para esto se considerar√° que un alumno ha reprobado el a√±o cuando el promedio de notas es inferior a 4.0 en la Escala Chilena, y se considerar√° destacado si posee notas superiores a 5.8 en todas las asignaturas (o sea notas superiores a 5.8 en `math score`, `reading score` y `writing score`).

Cree una funci√≥n que permita obtener tres Dataframes: 
- El primero deber√° poseer solamente los alumnos que han reprobado en la prestigiosa universidad.
- El segundo debe entregar un DataFrame similar al original, pero marcado con una "R" el promedio de notas de los alumnos reprobados.
- El tercero ser√° un Data Frame con los alumnos destacados ordenados de mayor a menor.

**To-Do:**

- [ ] Obtener DataFrame con los alumnos que reprobaron el a√±o.
- [ ] Obtener DataFrame similar al original, pero marcados con una "R" el atributo GPA de los alumnos reprobados.
- [ ] Obtener DataFrame con los alumnos destacados ordenados de mayor a menor.

**Respuesta:**

In [33]:
def reprobados_destacados(dataframe_in):
    resp = dataframe_in.copy()
    resp1 = resp[(resp['GPA'] < 4)]
    resp2 = resp.copy() 
    resp2['GPA'].loc[resp['GPA'] < 4] = 'R'
    resp3 = resp[(resp['math score'] > 5.8) & (resp['writing score'] > 5.8) & (resp['reading score'] > 5.8)].sort_values(by ='GPA', ascending = False)
    return resp1, resp2, resp3

In [34]:
dataframe1, dataframe2, dataframe3 = reprobados_destacados(df_grades)
dataframe1

<ipython-input-33-832cf442e79e>:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,GPA
0,Rita Courtney,female,group B,some high school,standard,none,3.22,3.76,3.76,3.58
13,Mikki Amaya,female,group A,high school,free/reduced,completed,3.04,3.88,3.46,3.46
26,Samuel Dougal,male,group C,master's degree,free/reduced,completed,3.76,3.52,3.76,3.68
55,Rodger Talavera,male,group B,high school,free/reduced,none,3.16,2.74,2.62,2.84
63,Morris Johnson,male,group A,associate's degree,free/reduced,completed,3.40,4.30,4.18,3.96
...,...,...,...,...,...,...,...,...,...,...
1371,Charles Harian,male,group C,some high school,free/reduced,completed,3.70,4.12,3.94,3.92
1373,Wendy Gunnell,female,group D,some high school,free/reduced,none,2.62,3.04,2.92,2.86
1389,Diana Costa,female,group C,high school,free/reduced,none,3.46,3.76,3.58,3.60
1391,Amy Sieving,female,group C,high school,standard,none,2.74,2.74,2.80,2.76
1394,Wanda Russell,female,group B,high school,free/reduced,completed,2.38,3.64,3.16,3.06

In [35]:
dataframe2

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,GPA
0,Rita Courtney,female,group B,some high school,standard,none,3.22,3.76,3.76,R
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,5.80,5.68,5.86,5.78
5,Brian Young,male,group C,some high school,standard,none,5.38,4.96,4.78,5.04
6,Howard Jimenez,male,group E,some high school,standard,completed,5.86,5.50,5.56,5.64
7,Wayne Wilson,male,group B,some high school,standard,completed,6.64,6.16,6.22,6.34
...,...,...,...,...,...,...,...,...,...,...
1392,Richard Young,male,group D,high school,standard,none,5.14,5.50,5.26,5.3
1394,Wanda Russell,female,group B,high school,free/reduced,completed,2.38,3.64,3.16,R
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,4.96,5.44,5.86,5.42
1397,Laurie Carter,female,group B,some high school,standard,completed,4.24,4.66,4.72,4.54
1399,Amanda Perez,female,group A,high school,standard,completed,5.08,5.80,5.56,5.48

In [36]:
dataframe3

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,GPA
677,Richard Pryor,male,group E,bachelor's degree,standard,completed,7.00,7.00,7.00,7.00
1352,Sandra Pompey,female,group E,associate's degree,standard,none,7.00,7.00,7.00,7.00
384,Elizabeth Beasley,female,group E,bachelor's degree,standard,none,7.00,7.00,7.00,7.00
475,Emma Gray,female,group E,bachelor's degree,standard,completed,6.94,7.00,7.00,6.98
279,Emma Brasher,female,group D,some high school,standard,completed,6.82,7.00,7.00,6.94
...,...,...,...,...,...,...,...,...,...,...
949,Rolando Widmer,male,group C,high school,standard,completed,5.92,6.04,5.92,5.96
296,Lucille Stanphill,female,group C,high school,standard,none,5.86,6.04,5.92,5.94
300,Steven Kelly,male,group D,some college,standard,none,5.86,5.92,6.04,5.94
1307,Peter Perez,male,group D,master's degree,standard,none,5.86,5.86,6.04,5.92
96,Harry Berry,male,group B,associate's degree,standard,completed,5.86,5.92,5.92,5.90

**Respuesta:**

```
Se crean los 3 sets de Datos seg√∫n lo especificado, 94 alumnos obtuvieron calificaciones destacadas mientras que 85 de ellos reprobaron
```

### 1.3.4 Consultas de Alumnos [0.5 Puntos]

Algunos padres (extremadamente entrometidos y...) preocupados por el desempe√±o de sus hijos, desean saber estos han aprobado o no el a√±o. Como la tarea de buscar a mano cada uno de estos alumnos en el `DataFrame` resulta demasiado tedioso, el rector le solicita crear una funci√≥n que tenga como entrada el `DataFrame` donde se realizar√° la busqueda y una lista con los nombres de los alumnos, luego la funci√≥n deber√° retornar un `DataFrame` con los nombres de los alumnos y el promedio general de cada uno. 

Creada la funci√≥n busque el promedio general de los siguientes alumnos en el segundo Data frame creado en la secci√≥n 1.3.3:

`['Lucille Stanphill','Marcus Mcfarland', 'Matthew Freeman', 'Dana Mojica', 'Paul Hyder', 'Jeffrey Korn', 'Robert Strain',
'Ronald Jett', 'Lorena Reed', 'Hazel Posey']`

**Hint:** Puede serle de utilidad utilizar `isin()`.

**Respuesta:**

In [37]:
def consulta_gpa(dataframe_in, lista_alumnos):
    resp = dataframe_in.copy()
    resp = resp[resp['names'].isin(lista_alumnos)][['names', 'GPA']]
    return resp


lista_alumnos = [
    "Lucille Stanphill",
    "Marcus Mcfarland",
    "Matthew Freeman",
    "Dana Mojica",
    "Paul Hyder",
    "Jeffrey Korn",
    "Robert Strain",
    "Ronald Jett",
    "Lorena Reed",
    "Hazel Posey",
]
consulta_gpa(dataframe2, lista_alumnos)

                  names   GPA
296   Lucille Stanphill  5.94
564    Marcus Mcfarland  4.86
637     Matthew Freeman     R
640         Dana Mojica     R
1054      Robert Strain   4.4
1065        Ronald Jett     R
1068        Hazel Posey     R
1195        Lorena Reed     R

### 1.3.5 Quintiles de Rendimiento [0.5 Puntos]

El rector, intrigado por saber si existe una relaci√≥n entre el nivel educacional de los padres y las notas de sus hijos les plantea estudiar dicha relaci√≥n. Para esto, les solicita que desde el `DataFrame` que posee a todos los alumnos (`DataFrame` obtenido tras la limpieza), generen una nueva columna que clasifique en quintiles de rendimiento para sus alumnos: `['Baj√≠simo', 'Bajo', 'Medio', 'Alto', 'Muy alto']`. (investigar `qcut()`)

Hecho esto, grafique a trav√©s de un scatter plot el nivel educacional de los padres v/s el promedio de los alumnos, utilice los cuantiles generados anteriormente para mostrar en que cuantil se encuentra cada uno de los datos.

Realizado el grafico, responda la siguiente pregunta: **¬øEs posible visualizar alguna tendencia en el gr√°fico?.**

**Respuesta:**

In [50]:
df_grades['GPA cuantiles'] = pd.qcut(df_grades['GPA'], 5, labels=['Baj√≠simo', 'Bajo', 'Medio', 'Alto', 'Muy alto'] )

In [51]:
df_grades.head()

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,GPA,GPA cuantiles
0,Rita Courtney,female,group B,some high school,standard,none,3.22,3.76,3.76,3.58,Baj√≠simo
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,5.80,5.68,5.86,5.78,Alto
5,Brian Young,male,group C,some high school,standard,none,5.38,4.96,4.78,5.04,Medio
6,Howard Jimenez,male,group E,some high school,standard,completed,5.86,5.50,5.56,5.64,Alto
7,Wayne Wilson,male,group B,some high school,standard,completed,6.64,6.16,6.22,6.34,Muy alto

In [52]:
# C√≥digo para quintiles 
# La variable que contenga los quintiles debe llamarse GPA cuantiles para que el gr√°fico funcione.

# C√≥digo de gr√°fico 
fig = px.scatter(
    df_grades.sort_values(by="GPA"),
    x="GPA",
    y="parental level of education",
    hover_data=["gender"],
    color="GPA cuantiles",
    title="GPA por Nivel de educaci√≥n de los padres",
    color_discrete_sequence=["tomato", "orange", "yellow", "greenyellow", "green"]
)

fig

```
A primera vista no pareciera haber una tendencia marcada, la media de todas las categor√≠as esta por sobre el 5 y los quintiles se cortan casi en los mismos puntos.
Donde si se Puede ver una diferencia es en el primer quintil, donde la media de ese quintil es mayor seg√∫n el nivel educacional de los padres, y los valores m√°s bajos de la muestra tambien coinciden con los de aquellos padres con menor nivel educativo.
```

# Conclusi√≥n
Eso ha sido todo para el lab de hoy, recuerden que el laboratorio tiene un plazo de entrega de una semana. Cualquier duda del laboratorio, no duden en contactarnos por mail o U-cursos.

<p align="center">
  <img src="https://media1.tenor.com/images/2f7df460196625edc45b8380d158e5ee/tenor.gif?itemid=16669403">
</p>

<br>
<center>
<img src="https://i.kym-cdn.com/photos/images/original/001/194/195/b18.png" width=100 height=50 />
</center>
<br>

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=87110296-876e-426f-b91d-aaf681223468' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>